@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content')
    @php
        $netClass = $summary['net'] > 0 ? 'profit' : ($summary['net'] < 0 ? 'loss' : 'zero');
        $netIcon = $summary['net'] > 0 ? 'fa-arrow-up' : ($summary['net'] < 0 ? 'fa-arrow-down' : 'fa-minus');
    @endphp
    <div class="dash-head"><div><h4 class="page_header mb-1">Dashboard</h4><p class="text-muted mb-0">A clear overview of your photography business.</p></div><a href="{{ route('dashboard.sessions.create') }}" class="btn btn-primary"><i class="fas fa-plus mr-1"></i> New session</a></div>
    <div class="row">
        <div class="col-sm-6 col-xl-3"><a href="{{ route('dashboard.clients.index') }}" class="dash-stat"><i class="fas fa-users blue"></i><span><small>Customers</small><strong>{{ number_format($counts['clients']) }}</strong></span><b>›</b></a></div>
        <div class="col-sm-6 col-xl-3"><a href="{{ route('dashboard.sessions.index') }}" class="dash-stat"><i class="fas fa-camera purple"></i><span><small>Sessions</small><strong>{{ number_format($counts['sessions']) }}</strong></span><b>›</b></a></div>
        <div class="col-sm-6 col-xl-3"><a href="{{ route('dashboard.galleries.index') }}" class="dash-stat"><i class="fas fa-images orange"></i><span><small>Galleries</small><strong>{{ number_format($counts['galleries']) }}</strong></span><b>›</b></a></div>
        <div class="col-sm-6 col-xl-3"><div class="dash-stat"><i class="far fa-calendar-alt green"></i><span><small>Next meeting</small><strong class="meeting">{{ $nextAppointment ? \Illuminate\Support\Carbon::parse($nextAppointment->date)->format('d M') . ' · ' . $nextAppointment->start_time : 'None scheduled' }}</strong></span></div></div>
    </div>
    <div class="dash-section"><h5>Finance overview</h5><a href="{{ route('dashboard.finance-report.index') }}">View report <i class="fas fa-arrow-right ml-1"></i></a></div>
    <div class="dash-finance"><div class="received"><span><i class="fas fa-hand-holding-usd"></i> Received</span><strong>{{ number_format($summary['received'], 2) }}</strong></div><div class="spent"><span><i class="fas fa-receipt"></i> Spent</span><strong>{{ number_format($summary['spent'], 2) }}</strong></div><div class="outstanding"><span><i class="fas fa-clock"></i> Still to collect</span><strong>{{ number_format($summary['outstanding'], 2) }}</strong></div><div class="{{ $netClass }}"><span><i class="fas fa-chart-line"></i> Profit / Loss</span><strong><i class="fas {{ $netIcon }} mr-1"></i>{{ number_format(abs($summary['net']), 2) }}</strong></div></div>
    <div class="row mt-4"><div class="col-lg-7 mb-3"><div class="dash-panel"><div class="dash-panel-head"><h5>Upcoming meetings</h5><a href="{{ route('photographer.appointments.index') }}">Calendar</a></div>
        @forelse ($nextAppointments as $appointment)<div class="next-meeting"><div class="date"><strong>{{ \Illuminate\Support\Carbon::parse($appointment->date)->format('d') }}</strong><span>{{ \Illuminate\Support\Carbon::parse($appointment->date)->format('M') }}</span></div><div><a class="appointment-link" href="{{ route('photographer.appointments.edit', $appointment->id) }}">{{ $appointment->name }}</a><small><i class="far fa-clock mr-1"></i>{{ $appointment->start_time }}{{ $appointment->end_time ? ' – ' . $appointment->end_time : '' }}</small><small>{{ $appointment->session->name ?? 'No session assigned' }}</small></div></div>
        @empty<div class="empty"><i class="far fa-calendar-plus"></i> No upcoming meeting. <a href="{{ route('photographer.appointments.create') }}">Schedule one</a></div>@endforelse
    </div></div><div class="col-lg-5 mb-3"><div class="dash-panel"><div class="dash-panel-head"><h5>Session value</h5><a href="{{ route('dashboard.sessions.index') }}">Sessions</a></div><div class="session-value"><span>Total amount across all sessions</span><strong>{{ number_format($summary['total_amount'], 2) }}</strong><small>{{ number_format($summary['outstanding'], 2) }} still to collect</small></div></div></div></div>
@stop

@section('css')
<style>
.dash-head,.dash-section,.dash-panel-head{display:flex;align-items:center;justify-content:space-between;gap:1rem}.dash-head{margin-bottom:1.25rem}.dash-head .page_header{margin:0!important}.dash-section{margin:1.75rem 0 .75rem}.dash-section h5,.dash-panel-head h5{margin:0;color:#334257;font-weight:700}.dash-section a,.dash-panel-head a{font-size:.85rem;font-weight:600}.dash-stat{display:flex;align-items:center;gap:.85rem;min-height:104px;margin-bottom:1rem;padding:1rem;border:1px solid #e6eaf0;border-radius:.65rem;background:#fff;box-shadow:0 5px 18px rgba(35,50,70,.06);color:#334257}.dash-stat:hover{color:#334257;text-decoration:none;transform:translateY(-2px)}.dash-stat>i{display:grid;width:45px;height:45px;place-items:center;border-radius:.6rem;font-size:1.15rem}.blue{color:#1769c2;background:#e7f1ff}.purple{color:#7155c7;background:#efeaff}.orange{color:#d97706;background:#fff3df}.green{color:#198754;background:#e7f7ed}.dash-stat small,.dash-finance span{display:block;color:#6c757d;font-size:.75rem;font-weight:700;text-transform:uppercase}.dash-stat strong{display:block;font-size:1.55rem}.dash-stat .meeting{font-size:1rem}.dash-stat>b{margin-left:auto;color:#aab3bf;font-size:1.5rem}.dash-finance{display:grid;grid-template-columns:repeat(4,1fr);overflow:hidden;border:1px solid #e6eaf0;border-radius:.65rem;background:#fff;box-shadow:0 5px 18px rgba(35,50,70,.07)}.dash-finance>div{padding:1rem 1.15rem;border-right:1px solid #e6eaf0}.dash-finance>div:last-child{border:0}.dash-finance strong{display:block;margin-top:.35rem;font-size:1.35rem}.received strong,.profit strong{color:#198754}.spent strong,.loss strong{color:#dc3545}.outstanding strong{color:#d98b00}.zero strong{color:#6c757d}.dash-panel{height:100%;padding:1.15rem;border:1px solid #e6eaf0;border-radius:.65rem;background:#fff;box-shadow:0 5px 18px rgba(35,50,70,.06)}.next-meeting{display:flex;align-items:center;gap:1rem;margin-top:1rem;padding-bottom:1rem;border-bottom:1px solid #edf0f3}.next-meeting:last-child{border-bottom:0;padding-bottom:0}.next-meeting .date{display:flex;flex-direction:column;align-items:center;min-width:54px;padding:.4rem;border-radius:.45rem;color:#1769c2;background:#e7f1ff}.date strong{font-size:1.25rem}.date span{font-size:.72rem;font-weight:700}.next-meeting small{display:block;color:#6c757d;margin-top:.2rem}.appointment-link{color:#334257;font-weight:700}.appointment-link:hover{color:#1769c2;text-decoration:none}.empty{padding:2rem 0;color:#6c757d}.empty i{color:#1769c2;margin-right:.5rem}.session-value{padding-top:1.1rem}.session-value span,.session-value small{display:block;color:#6c757d}.session-value strong{display:block;margin:.3rem 0;color:#334257;font-size:2rem}@media(max-width:767.98px){.dash-head{align-items:flex-start;flex-direction:column}.dash-finance{grid-template-columns:repeat(2,1fr)}.dash-finance>div:nth-child(2){border-right:0}.dash-finance>div:nth-child(-n+2){border-bottom:1px solid #e6eaf0}}
</style>
@stop
