@extends('adminlte::page')

@section('title', 'Portfolio Settings')

@section('content')
    @php
        $portfolioPort = request()->getPort();
        $portfolioUrl = request()->getScheme() . '://' . $photographer->subdomain . '.' . env('APP_DOMAIN')
            . (in_array($portfolioPort, [80, 443]) ? '' : ':' . $portfolioPort) . '/portfolio';
    @endphp
    <div class="portfolio-settings-head">
        <div><h4 class="page_header mb-1">Portfolio</h4><p class="text-muted mb-0">Create a public home for your best work.</p></div>
        <a class="btn btn-outline-primary" target="_blank" href="{{ $portfolioUrl }}"><i class="fas fa-external-link-alt mr-1"></i> View portfolio</a>
    </div>
    <form method="POST" action="{{ route('dashboard.portfolio.update') }}" enctype="multipart/form-data">
        @csrf @method('PUT')
        <div class="row">
            <div class="col-lg-8"><div class="ibox-content portfolio-settings-card">
                <h5>Brand & introduction</h5>
                <div class="form-group"><label for="portfolio_title">Portfolio title</label><input id="portfolio_title" name="portfolio_title" class="form-control" maxlength="100" value="{{ old('portfolio_title', $photographer->portfolio_title ?: $photographer->user->name) }}" placeholder="e.g. Maria El-Sayed Photography">@error('portfolio_title')<small class="text-danger">{{ $message }}</small>@enderror</div>
                <div class="form-group"><label for="portfolio_bio">Introduction</label><textarea id="portfolio_bio" name="portfolio_bio" class="form-control" rows="4" maxlength="1000" placeholder="Tell visitors about your photography style and services.">{{ old('portfolio_bio', $photographer->portfolio_bio) }}</textarea>@error('portfolio_bio')<small class="text-danger">{{ $message }}</small>@enderror</div>
                <div class="form-group"><label for="portfolio_cover">Portfolio cover image</label><p class="text-muted small mb-2">This is the main image visitors see first. Recommended: landscape image, at least 1600 × 900 px.</p><div class="portfolio-cover-upload">@if($photographer->portfolio_cover_url)<img id="portfolioCoverPreview" src="{{ $photographer->portfolio_cover_url }}" alt="Portfolio cover preview">@else<i id="portfolioCoverIcon" class="far fa-image"></i><img id="portfolioCoverPreview" alt="Portfolio cover preview" style="display:none">@endif<div><label class="portfolio-cover-button mb-1" for="portfolio_cover"><i class="fas fa-cloud-upload-alt"></i>{{ $photographer->portfolio_cover_url ? 'Change cover image' : 'Upload cover image' }}</label><small class="d-block text-muted">JPG, PNG or WEBP · Maximum 5 MB</small></div><input id="portfolio_cover" name="portfolio_cover" type="file" accept="image/*" class="d-none"></div>@error('portfolio_cover')<small class="text-danger">{{ $message }}</small>@enderror</div>
                <hr><h5>Choose your portfolio style</h5><p class="text-muted small mb-3">Select a design to see how your public portfolio will be structured.</p>
                @php($selectedTheme = old('portfolio_theme', 'bold'))
                <div class="theme-picker">
                    <label class="theme-choice"><input type="radio" name="portfolio_theme" value="bold" {{ $selectedTheme === 'bold' ? 'checked' : '' }}><span class="theme-preview theme-preview--bold"><i></i><b></b><em></em><em></em><em></em></span><strong>Bold Showcase</strong><small>High-impact, immersive work</small></label>
                </div>
                <div class="row mt-4"><div class="col-md-6 form-group"><label>Primary color</label><input type="color" name="portfolio_primary_color" class="form-control color-input" value="{{ old('portfolio_primary_color', $photographer->portfolio_primary_color) }}">@error('portfolio_primary_color')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="col-md-6 form-group"><label>Accent color</label><input type="color" name="portfolio_accent_color" class="form-control color-input" value="{{ old('portfolio_accent_color', $photographer->portfolio_accent_color) }}">@error('portfolio_accent_color')<small class="text-danger">{{ $message }}</small>@enderror</div></div>
                <hr><h5>Contact details</h5><p class="text-muted small mb-3">Your account email is used by default. Add the details you want visitors to see.</p>
                <div class="row"><div class="col-md-6 form-group"><label for="portfolio_contact_email">Email</label><input id="portfolio_contact_email" type="email" name="portfolio_contact_email" class="form-control" value="{{ old('portfolio_contact_email', $photographer->portfolio_contact_email ?: $photographer->user->email) }}">@error('portfolio_contact_email')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="col-md-6 form-group"><label for="portfolio_contact_phone">Phone</label><input id="portfolio_contact_phone" type="text" name="portfolio_contact_phone" class="form-control" value="{{ old('portfolio_contact_phone', $photographer->portfolio_contact_phone) }}" placeholder="+20 10 0000 0000">@error('portfolio_contact_phone')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="col-md-6 form-group"><label for="portfolio_instagram">Instagram</label><input id="portfolio_instagram" type="text" name="portfolio_instagram" class="form-control" value="{{ old('portfolio_instagram', $photographer->portfolio_instagram) }}" placeholder="@yourhandle">@error('portfolio_instagram')<small class="text-danger">{{ $message }}</small>@enderror</div><div class="col-md-6 form-group"><label for="portfolio_footer_text">Footer text</label><input id="portfolio_footer_text" type="text" name="portfolio_footer_text" class="form-control" maxlength="255" value="{{ old('portfolio_footer_text', $photographer->portfolio_footer_text ?: 'Photography by ' . ($photographer->portfolio_title ?: $photographer->user->name)) }}">@error('portfolio_footer_text')<small class="text-danger">{{ $message }}</small>@enderror</div></div>
                <div class="custom-control custom-switch mb-4"><input type="hidden" name="portfolio_show_contact" value="0"><input type="checkbox" class="custom-control-input" id="portfolio_show_contact" name="portfolio_show_contact" value="1" {{ old('portfolio_show_contact', $photographer->portfolio_show_contact) ? 'checked' : '' }}><label class="custom-control-label" for="portfolio_show_contact">Show contact email on public portfolio</label></div>
                <button class="btn btn-primary"><i class="fas fa-save mr-1"></i> Save portfolio</button>
            </div></div>
            <div class="col-lg-4"><div class="ibox-content portfolio-settings-card"><h5>How it works</h5><p class="text-muted small">Your portfolio automatically shows galleries marked <strong>Public</strong>.</p><ol class="portfolio-steps"><li>Create or edit a gallery.</li><li>Enable <strong>Is Public</strong>.</li><li>It appears on your portfolio automatically.</li></ol><a href="{{ route('dashboard.galleries.index') }}" class="btn btn-light btn-block">Manage galleries</a></div></div>
        </div>
    </form>
    <div class="modal fade" id="coverCropModal" tabindex="-1" role="dialog" aria-labelledby="coverCropModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered" role="document"><div class="modal-content">
            <div class="modal-header"><div><h5 class="modal-title" id="coverCropModalTitle">Crop portfolio cover</h5><small class="text-muted">Adjust the image to fit the 16:9 cover area.</small></div><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
            <div class="modal-body portfolio-crop-body"><img id="portfolioCropImage" alt="Crop portfolio cover"></div>
            <div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button><button type="button" id="applyPortfolioCrop" class="btn btn-primary"><i class="fas fa-check mr-1"></i> Use cropped image</button></div>
        </div></div>
    </div>
@stop

@section('css')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.css">
<style>.portfolio-settings-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:1.25rem}.portfolio-settings-card{padding:1.4rem;margin-bottom:1rem}.portfolio-settings-card h5{font-weight:700;color:#334257;margin-bottom:.5rem}.portfolio-settings-card hr{margin:1.8rem 0}.color-input{height:42px;padding:.25rem}.portfolio-cover-upload{display:flex;align-items:center;gap:1rem;min-height:96px;padding:.85rem;border:1px dashed #9eb5cc;border-radius:.6rem;background:linear-gradient(135deg,#fbfdff,#f3f7fb)}.portfolio-cover-upload img,.portfolio-cover-upload>i{width:124px;height:76px;border-radius:.4rem;object-fit:cover}.portfolio-cover-upload>i{display:grid;place-items:center;background:#e4edf6;color:#6684a2;font-size:1.55rem}.portfolio-cover-button{display:inline-flex;align-items:center;gap:.45rem;padding:.55rem .85rem;border:0;border-radius:.35rem;background:#1455ac;color:#fff!important;font-size:.82rem;font-weight:700;cursor:pointer;box-shadow:0 3px 8px rgba(20,85,172,.2);transition:.18s}.portfolio-cover-button:hover{background:#0e478f;transform:translateY(-1px)}.portfolio-crop-body{min-height:390px;max-height:65vh;background:#18202b}.portfolio-crop-body img{display:block;max-width:100%}.portfolio-steps{padding-left:1.15rem;color:#6c757d}.portfolio-steps li{margin-bottom:.75rem}.theme-picker{display:grid;grid-template-columns:minmax(220px,330px);gap:1rem}.theme-choice{display:block;margin:0;cursor:pointer}.theme-choice input{position:absolute;opacity:0}.theme-preview{position:relative;display:block;height:145px;padding:13px;overflow:hidden;border:2px solid transparent;border-radius:.55rem;background:#f5f6f8;transition:.18s}.theme-choice input:checked+.theme-preview{border-color:#1455ac;box-shadow:0 0 0 3px rgba(20,85,172,.13)}.theme-choice strong{display:block;margin:.65rem 0 .12rem;color:#334257;font-size:.9rem}.theme-choice small{color:#6c757d;font-size:.76rem}.theme-preview i{display:block;width:30%;height:5px;margin-bottom:10px;background:#26374b}.theme-preview b{display:block;width:76%;height:16px;margin-bottom:13px;background:#fff}.theme-preview em{display:inline-block;height:72px;background:linear-gradient(135deg,#335c7b,#ba8b55)}.theme-preview em:nth-of-type(1){width:62%;margin-right:2%}.theme-preview em:nth-of-type(2){width:36%}.theme-preview em:nth-of-type(3){display:none}.theme-preview--bold{background:#172230}.theme-preview--bold i{background:#fff}@media(max-width:767.98px){.theme-picker{grid-template-columns:1fr}.theme-preview{height:125px}.portfolio-crop-body{min-height:260px}}@media(max-width:575.98px){.portfolio-settings-head{align-items:flex-start;flex-direction:column}}</style>
@stop

@section('js')
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.6.2/cropper.min.js"></script>
<script>$(function(){let cropper,selectedFile,cropApplied=false;const input=document.getElementById('portfolio_cover'),image=document.getElementById('portfolioCropImage'),preview=document.getElementById('portfolioCoverPreview');input.addEventListener('change',function(){selectedFile=this.files[0];if(!selectedFile)return;cropApplied=false;image.src=URL.createObjectURL(selectedFile);$('#coverCropModal').modal('show');});$('#coverCropModal').on('shown.bs.modal',function(){if(cropper)cropper.destroy();cropper=new Cropper(image,{aspectRatio:16/9,viewMode:1,autoCropArea:1,responsive:true});}).on('hidden.bs.modal',function(){if(cropper){cropper.destroy();cropper=null;}if(!cropApplied)input.value='';});document.getElementById('applyPortfolioCrop').addEventListener('click',function(){if(!cropper||!selectedFile)return;cropper.getCroppedCanvas({width:1600,height:900,imageSmoothingQuality:'high'}).toBlob(function(blob){const croppedFile=new File([blob],'portfolio-cover.jpg',{type:'image/jpeg'}),transfer=new DataTransfer();transfer.items.add(croppedFile);input.files=transfer.files;preview.src=URL.createObjectURL(blob);preview.style.display='block';const icon=document.getElementById('portfolioCoverIcon');if(icon)icon.style.display='none';cropApplied=true;$('#coverCropModal').modal('hide');},'image/jpeg',.9);});});</script>
@stop
